import mongoose from 'mongoose';

// Charges fixes (loyer, électricité, assurance, etc.)
const ExpenseSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String },
  category: {
    type: String,
    enum: ['fixed', 'variable'],
    required: true,
    default: 'fixed'
  },
  subcategory: { type: String }, // Loyer, Électricité, Internet, Salaires...
  amount: { type: Number, required: true },
  month: { type: String, required: true }, // 'YYYY-MM'
  paidAt: { type: Date, required: true },
  isAutoGenerated: { type: Boolean, default: false } // true si généré depuis masse salariale
}, { timestamps: true });

ExpenseSchema.index({ month: 1, category: 1 });

export default mongoose.model('Expense', ExpenseSchema);
